# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0559b432e14c62f2fa4cae78246c1df8855aa5beaffd549dd1960bc9b95df9fdd10303f91dd57b7fbb9b21b1eb62727420071aebe8bf9b06265a0beeddd41494

test:
  secret_key_base: 358f75599c9e5cbf790d4a774079dedc9593f5fc83ee28e39c18ddcef1da76c022b16a711411887cf17d53627dd65e8125085aa175e8384a431caf7794267321

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
